import { store } from "./store.js";

const fs = window.api.fs;
const path = window.api.path;

const defaultFr = {
  toolbar_add: "Ajouter une instance",
  toolbar_import: "Importer",
  toolbar_builder: "Créer un Modpack",
  toolbar_catalog: "Catalogue de Contenu",
  toolbar_settings: "Paramètres Globaux",
  toolbar_logs: "Afficher les logs",
  toolbar_manage: "Gérer",
  toolbar_stats: "Statistiques",
  search_inst: "Rechercher une instance...",
  sort_name: "Trier par Nom",
  sort_last: "Dernière utilisation",
  sort_time: "Temps de jeu",
  panel_title: "Sélectionnez une instance",
  panel_time: "Temps :",
  panel_last: "Dernier :",
  btn_launch: "Lancer",
  btn_stop: "Forcer l'arrêt",
  btn_settings: "Paramètres de l'instance",
  btn_mods: "Gestionnaire de Mods",
  btn_saves: "Voir les mondes",
  btn_gallery: "Galerie de Captures",
  btn_folder: "Dossier de l'instance",
  btn_delete: "Supprimer",
  btn_copy: "Copier l'instance",
  btn_export: "Exporter l'instance",
  status_ready: "Prêt",
  modal_cancel: "Annuler",
  modal_save: "Sauvegarder",
  modal_close: "Fermer",
  modal_apply: "Appliquer",
  modal_create: "Créer",
  modal_add: "Ajouter",
  btn_search: "Chercher",
  tab_gen: "Général",
  tab_mods: "Mods",
  tab_shaders: "Shaders",
  tab_resourcepacks: "Packs de Textures",
  tab_servers: "Serveurs",
  tab_backups: "Sauvegardes",
  tab_java: "Configuration",
  tab_notes: "Notes",
  tab_updates: "Mises à jour",
  btn_check_launcher_updates: "Vérifier les mises à jour",
  msg_up_to_date: "Le launcher est à jour.",
  msg_update_found: "Une mise à jour a été trouvée",
  msg_download_update: "Voulez-vous la télécharger en arrière-plan ?",
  lbl_backup_mode: "Sauvegarde Automatique des Mondes",
  lbl_backup_limit: "Nombre de sauvegardes à conserver :",
  opt_none: "Désactivé",
  opt_launch: "Au lancement du jeu",
  opt_close: "A la fermeture du jeu",
  txt_backup_desc: "Le launcher conservera automatiquement vos sauvegardes dans le dossier 'backups'.",
  btn_open_backups: "Ouvrir le dossier des sauvegardes",
  lbl_lang: "Langue du Launcher",
  lbl_ram: "Mémoire RAM (Mo) :",
  lbl_java: "Chemin Java par défaut",
  btn_scan: "Scanner",
  lbl_fav_server: "Serveur favori",
  lbl_beta: "Afficher les Bêtas",
  lbl_loader: "Type de chargeur",
  lbl_loader_version: "Version du chargeur",
  lbl_inst_name: "Nom de l'instance",
  lbl_installed_mods: "Vos Mods Installés",
  lbl_installed_shaders: "Vos Shaders",
  lbl_installed_rps: "Vos Packs de Textures",
  btn_check_updates: "Vérifier les MAJ",
  btn_dl_mods: "Télécharger de nouveaux mods",
  lbl_width: "Largeur",
  lbl_height: "Hauteur",
  lbl_jvm: "Arguments JVM",
  lbl_offline: "Ajouter un profil Hors-Ligne",
  tab_appearance: "Apparence",
  lbl_accent: "Couleur Principale",
  lbl_bg: "Image de fond",
  btn_browse: "Parcourir",
  btn_clear: "Effacer",
  lbl_blur: "Flou du fond",
  lbl_darkness: "Assombrissement du fond",
  lbl_panel_opacity: "Opacité de l'interface (Panneaux)",
  lbl_group: "Dossier / Catégorie de l'instance",
  msg_mod_added: "Ajouté à l'instance avec succès !",
  msg_select_inst: "Sélectionnez une instance d'abord !",
  msg_search_java: "Recherche de Java...",
  msg_java_found: "version(s) de Java trouvée(s).",
  msg_extract_java: "Extraction de Java...",
  msg_err_java: "Erreur Java",
  msg_backup: "Création de la sauvegarde...",
  msg_no_screen: "Aucune capture d'écran.",
  msg_launching: "Lancement de ",
  msg_check_java: "Vérification de Java...",
  msg_sync_servers: "Synchronisation des serveurs...",
  msg_install_fabric: "Installation de Fabric...",
  msg_prep_files: "Préparation des fichiers...",
  msg_dl: "Téléchargement : ",
  msg_game_stop: "Le jeu s'est arrêté",
  msg_conn_ms: "Connexion...",
  ms_device_title: "Connexion Microsoft",
  ms_device_help: "Copie le code ci-dessous, ouvre la page Microsoft, puis saisis le code quand le site le demande.",
  ms_device_copy: "Copier le code",
  ms_device_open: "Ouvrir la page Microsoft",
  ms_device_copied: "Code copié dans le presse-papiers.",
  ms_device_status_1: "En attente : valide le code sur le site Microsoft.",
  ms_device_status_2: "Finalisation côté launcher (serveurs Xbox / Mojang)… Peut prendre une dizaine de secondes.",
  ms_device_footer: "Tu peux fermer l’onglet du navigateur une fois la connexion acceptée ; cette fenêtre se fermera quand le compte sera enregistré.",
  ms_device_cancel: "Annuler",
  ms_device_cancelled: "Connexion Microsoft annulée.",
  msg_err_ms: "Erreur Microsoft : ",
  msg_err_sys: "Erreur système : ",
  msg_remove_acc: "Retirer ce compte ?",
  msg_copy: "Copie en cours...",
  msg_delete_inst: "Supprimer l'instance ?",
  msg_compress: "Compression...",
  msg_extract: "Extraction...",
  msg_check_updates: "Vérification des mises à jour...",
  msg_updating: "Mise à jour : ",
  msg_mods_updated: "mod(s) mis à jour !",
  msg_mods_uptodate: "Mods déjà à jour !",
  msg_dl_mod: "Téléchargement en cours...",
  msg_no_compat: "Aucun fichier compatible.",
  msg_deps: "Téléchargement des dépendances...",
  msg_install_success: "Installation réussie !",
  msg_err_dl: "Erreur lors du téléchargement.",
  msg_ping: "Ping...",
  msg_online: "En ligne",
  msg_offline: "Hors-ligne",
  msg_err_ping: "Erreur",
  msg_no_mods: "Aucun mod local installé.",
  msg_no_shaders: "Aucun shader installé.",
  msg_no_rps: "Aucun pack de textures installé.",
  msg_no_servers: "Aucun serveur enregistré.",
  msg_no_acc: "Aucun profil enregistré.",
  opt_modpack: "Modpacks",
  btn_install: "Installer",
  msg_dl_mods_pack: "Téléchargement des mods",
  msg_logs_copied: "Logs copiés dans le presse-papier !",
  msg_err_mrpack_invalid: "Ce n'est pas un fichier .mrpack valide (modrinth.index.json manquant).",
  msg_err_mrpack: "Erreur Modpack : ",
  btn_copy_logs: "Copier",
  modal_confirm: "Confirmation",
  btn_yes: "Oui",
  btn_no: "Non",
  msg_err_cf: "Les modpacks CurseForge (.zip) sont bloqués par Overwolf. Cherchez la version Modrinth (.mrpack) dans le catalogue !",
  msg_err_path: "Erreur : Chemin introuvable (Lancez l'app via npm start !)",
  msg_err_format: "Format non supporté ! (.mrpack, .zip, .jar, .png)",
  modal_worlds_title: "Gestion des Mondes",
  msg_no_worlds: "Aucun monde trouvé.",
  btn_world_backup: "Sauvegarder",
  btn_world_copy: "Copier",
  msg_copy_world_loading: "Copie du monde en cours...",
  msg_world_copied: "Monde copié avec succès !",
  msg_delete_world_confirm: "Voulez-vous vraiment supprimer ce monde définitivement ?",
  msg_world_deleted: "Monde supprimé !",
  msg_world_backedup: "Sauvegarde créée dans le dossier 'backups' !",
  lbl_folder: "Dossier : ",
  lbl_created: "Créé le : ",
  lbl_played: "Joué le : ",
  modal_stats_title: "Tableau de Bord",
  stat_total_time: "Temps de jeu total",
  stat_total_instances: "Instances créées",
  stat_total_mods: "Mods installés",
  stat_fav_instance: "Instance favorite : ",
  stat_disk_usage: "Espace disque utilisé",
  txt_players: "Joueurs",
  btn_auto_ram: "Optimiser",
  tt_auto_ram: "Analyse votre PC et vos mods pour allouer la RAM parfaite (Min 4Go).",
  msg_ram_optimized: "RAM optimisée à ",
  modal_updates_title: "Mises à jour disponibles",
  msg_updates_available: "Les mods suivants vont être mis à jour :",
  btn_update_all: "Tout installer",
  msg_no_updates: "Tous vos mods sont à jour !",
  lbl_options_profile: "Profil d'Options (options.txt)",
  txt_options_desc: "Sélectionnez une instance pour que ses touches deviennent celles par défaut.",
  btn_save_options: "Définir comme défaut",
  msg_options_saved: "Profil d'options sauvegardé !",
  msg_no_options_found: "Aucun options.txt trouvé. Lancez le jeu au moins une fois sur cette instance !",
  msg_files_added: "fichier(s) ajouté(s) !",
  modal_import_mc: "Importer un monde officiel",
  btn_import_official_world: "Importer depuis .minecraft",
  msg_no_mc_worlds: "Aucun monde trouvé dans .minecraft",
  msg_world_imported: "Monde importé avec succès !",
  lbl_sync_options: "Touches & Options",
  txt_sync_options: "Écrase les paramètres avec votre profil par défaut.",
  btn_sync_now: "Injecter",
  msg_force_sync_success: "Touches synchronisées avec succès !",
  msg_force_sync_error: "Aucun profil par défaut défini dans les Paramètres Globaux.",
  lbl_visibility: "Comportement au lancement",
  opt_keep: "Garder le launcher ouvert",
  opt_hide: "Cacher le launcher (Mode Fantôme)",
  btn_auto_connect: "Auto",
  msg_warn_deps: "Dépendance manquante potentielle : ",
  btn_show: "Afficher",
  btn_hide: "Masquer",
  lbl_news: "Actualités Minecraft",
  msg_server_search: "Recherche du serveur",
  msg_server_offline_desc: "Le serveur est actuellement hors-ligne ou injoignable.",
  msg_server_error: "Erreur de connexion à",
  lbl_players: "joueurs",
  modal_export_zip: "Export Complet (.zip)",
  txt_export_zip_desc: "Contient absolument tous vos mods et mondes (Fichier lourd).",
  modal_export_mrpack: "Export Léger (.mrpack)",
  txt_export_mrpack_desc: "Génère un fichier de quelques Ko idéal pour partager avec vos amis.",
  lbl_live_stats: "Monitoring Système",
  lbl_live_ram: "RAM Globale :",
  lbl_live_cpu: "Charge CPU :",
  msg_mrpack_analyze: "Analyse des mods et génération du .mrpack...",
  msg_mrpack_success: "Export .mrpack réussi !",
  msg_mrpack_error: "Erreur lors de l'export .mrpack",
  lbl_discord_playing: "Joue sur",
  lbl_discord_solo: "En jeu",
  btn_discord_download: "Télécharger Gens Launcher",
  msg_dl_browser: "Lien de téléchargement sécurisé... Ouverture du navigateur.",
  msg_cf_api_req: "CurseForge nécessite une clef API.\nAjoutez-la dans les Paramètres Globaux du launcher.",
  msg_cf_api_invalid: "Clef API CurseForge invalide ou erreur réseau.",
  lbl_warning: "[!]",
  lbl_accounts_title: "Comptes",
  lbl_add_microsoft: "Ajouter Microsoft",
  lbl_add_offline: "Ajouter Hors-Ligne",
  lbl_use_account: "Utiliser le compte",
  lbl_skin_cape: "Skin & Cape",
  lbl_active_acc: "Actif",
  modal_skin_title: "Visionneuse 3D de Skin",
  btn_test_skin: "Tester un Skin (Aperçu)",
  btn_export_skin: "Exporter le Skin actuel",
  btn_change_mojang: "Changer sur Minecraft.net",
  tip_skin_3d: "💡 Astuce : Cliquez et glissez pour pivoter. Molette pour zoomer.",
  btn_dl_shaders: "Télécharger de nouveaux shaders",
  btn_dl_rps: "Télécharger de nouveaux packs",
  ph_java_local: "Laisser vide pour utiliser le global",
  lbl_group_general: "Général",
  lbl_current_version: "Version actuelle :",
  ph_inst_name: "Ma Survie",
  ph_filter_logs: "Filtrer les logs...",
  msg_calc: "Calcul...",
  lbl_gb: "Go",
  msg_open_mp: "Ouverture de la page du modpack...",
  msg_dl_mp: "Téléchargement du modpack...",
  msg_install_mp: "Installation du modpack...",
  msg_patch_notes: "Correction de bugs et améliorations.",
  msg_update_ready: "Téléchargement terminé ! Voulez-vous redémarrer le launcher pour installer la mise à jour ?",
  lbl_cf_api: "Clé API CurseForge (Optionnel)",
  txt_cf_api_desc: "Nécessaire uniquement pour utiliser le catalogue CurseForge. Obtenez une clé gratuite sur EternalDeveloper.",
  msg_err_name_req: "Le nom de l'instance est obligatoire !",
  msg_profile_disabled: "Profil par défaut désactivé.",
  msg_err_install_loader: "Impossible d'installer le chargeur pour cette version.",
  msg_force_stop_sent: "Tentative d'arrêt forcé envoyée.",
  lbl_discord_rpc: "Discord RPC (Statut en jeu)",
  lbl_multi_inst: "Lancement Multi-instances",
  opt_enabled: "Activé",
  opt_disabled: "Désactivé",
  btn_folder_inst: "Dossier de l'instance",
  btn_folder_saves: "Dossier Mondes",
  btn_folder_backups: "Dossier Sauvegardes",
  btn_folder_screens: "Dossier Captures",
  btn_restore: "Restaurer",
  msg_restore_confirm: "Voulez-vous vraiment restaurer \"{name}\" ?\n\n⚠️ Le monde actuel sera supprimé et remplacé par cette sauvegarde !",
  msg_restore_loading: "Restauration de la sauvegarde...",
  msg_restore_success: "Monde restauré avec succès !",
  msg_restore_err: "Erreur lors de la restauration : ",
  msg_no_backups: "Aucune sauvegarde trouvée.",
  msg_del_screen_confirm: "Voulez-vous vraiment supprimer cette capture d'écran ?",
  msg_screen_deleted: "Capture d'écran supprimée.",
  msg_del_screen_err: "Erreur lors de la suppression : ",
  modal_restore_title: "Restaurer une sauvegarde",
  lbl_auto_update: "Télécharger les MAJ automatiquement",
  msg_update_dl_prompt: "Une nouvelle version du launcher est disponible. Voulez-vous la télécharger ?",
  msg_update_restart: "Mise à jour prête ! Voulez-vous redémarrer le launcher maintenant ?",
  lbl_running: "En cours",
  msg_req_mc_120: "Nécessite Minecraft 1.20+",
  msg_shader_deleted: "Shader supprimé !",
  msg_rp_deleted: "Pack supprimé !",
  msg_err_delete: "Erreur lors de la suppression",
  msg_game_running: "Jeu en cours d'exécution...",
  msg_install_quilt: "Installation de Quilt...",
  discord_in_menu: "Dans les menus",
  discord_playing_on: "Sur un serveur",
  discord_playing_solo: "En survie Solo",
  lbl_servers_profile: "Profil de Serveurs (servers.dat)",
  txt_servers_desc: "Copie automatiquement les serveurs de cette instance vers toutes les nouvelles instances.",
  btn_save_default: "Définir comme défaut",
  opt_none_disable: "Aucun (Désactiver)",
  msg_profile_saved: "Profil sauvegardé !",
  lbl_java_opti: "Profil d'Optimisation Java (Anti-Lag)",
  txt_java_opti_desc: "Sélectionnez un profil pour injecter automatiquement les meilleurs arguments.",
  opt_java_none: "Aucun (Standard)",
  opt_java_aikar: "Aikar's Flags (Recommandé pour la majorité)",
  opt_java_zgc: "ZGC (Basse latence - Java 21+ requis)",
  desc_java_none: "Standard : Laisse le jeu gérer la mémoire avec les paramètres par défaut de votre version de Java.",
  desc_java_aikar: "Aikar's Flags : Les arguments les plus célèbres de la communauté Minecraft. Ils forcent le jeu à nettoyer la mémoire RAM en permanence et de façon intelligente. Avantage : Supprime presque totalement les 'pics de lag' (freezes d'une seconde). Parfait pour les gros modpacks.",
  desc_java_zgc: "Z Generational (ZGC) : Une technologie ultra-moderne de Java. Elle divise le temps de traitement de la RAM par 10. Avantage : Temps de pause quasiment invisibles. Idéal pour le PvP compétitif et la fluidité absolue. (Attention : Ne fonctionne que si l'instance utilise Java 21 ou supérieur).",
  stat_mobs: "Mobs Tués",
  stat_distance: "Distance (Marche)",
  stat_jumps: "Sauts",
  lbl_km: "km",
  lbl_cache_title: "Fichiers temporaires (Cache)",
  txt_cache_desc: "Installeurs Forge, archives Java et anciens exports.",
  lbl_freed_space: "Espace libérable :",
  btn_clean: "Nettoyer",
  lbl_graph_title: "⏱ Temps de jeu — 7 derniers jours",
  lbl_new_version: "Nouvelle version disponible :",
  btn_start_update: "Télécharger et Installer",
  msg_update_found_bg: "Mise à jour trouvée ! Téléchargement en arrière-plan...",
  msg_login_success: "Connexion réussie !",
  msg_skin_exported: "Skin exporté avec succès !",
  msg_err_skin_export: "Erreur lors de l'exportation du skin.",
  msg_err_reserved_name: "Ce nom est invalide car réservé par le système.",
  msg_err_similar_name: "Une instance avec un nom similaire (même dossier) existe déjà !",
  msg_err_create_folder: "Erreur système : Impossible de créer le dossier.",
  msg_err_rename_folder: "Erreur système : Impossible de renommer le dossier.",
  modal_builder_title: "Créateur de Modpack Personnalisé",
  lbl_modpack_name: "Nom du Modpack",
  ph_modpack_name: "Mon Super Modpack",
  lbl_version: "Version",
  lbl_your_selection: "Votre sélection",
  btn_create_install: "Créer & Installer",
  opt_mods_type: "Mods",
  opt_shaders_type: "Shaders",
  opt_rp_type: "Ressources",
  ph_search_modrinth: "Rechercher sur Modrinth...",
  msg_builder_no_name: "Donnez un nom à votre Modpack !",
  msg_builder_no_mods: "Ajoutez au moins un élément !",
  msg_builder_name_taken: "Une instance avec ce nom existe déjà.",
  msg_builder_creating: "Création de l'instance...",
  msg_builder_downloading: "Téléchargement :",
  msg_builder_success: "Modpack créé avec succès !",
  msg_builder_searching: "Recherche en cours...",
  msg_builder_no_results: "Aucun résultat pour cette version / ce loader.",
  msg_builder_empty_pack: "Le pack est vide.",
  msg_builder_search_err: "Erreur de recherche.",
  btn_added: "Ajouté",
  btn_add_to_pack: "Ajouter",
  lbl_type_mod: "Mod",
  lbl_type_shader: "Shader",
  lbl_type_pack: "Pack de Textures",
  msg_crash_prompt: "Le jeu a planté ! \n\nL'analyseur a détecté que [ {mod} ] est responsable.\nVoulez-vous le désactiver ?",
  msg_analyze_cf: "Analyse du Modpack CurseForge...",
  msg_prep_loader: "Préparation de ",
  msg_dl_loader: "Téléchargement de ",
  msg_drop_install: "Relâchez pour installer",
  lbl_mc_console: "Console Minecraft",
  modal_icon_gallery_title: "Galerie d'icônes",
  lbl_eco_mode: "Mode Éco (Performances)",
  opt_eco_disabled: "Désactivé (Recommandé)",
  opt_eco_enabled: "Activé (Pour les petits PC)",
  lbl_java_25: "Java 25",
  desc_java_25: "Pour Minecraft 26.1 et +",
  lbl_java_21: "Java 21",
  desc_java_21: "Pour Minecraft 1.20.5 à 26.1",
  lbl_java_17: "Java 17",
  desc_java_17: "Pour Minecraft 1.17 à 1.20.4",
  lbl_java_8: "Java 8",
  desc_java_8: "Pour Minecraft 1.16.5 et inférieur",
  btn_java_dl: "Télécharger",
  btn_java_installed: "Installé",
  lbl_ms_account: "Compte Microsoft",
  lbl_offline_account: "Hors-Ligne (Crack)",
  msg_skin_preview: "Aperçu du skin chargé en 3D !",
  msg_delete_confirm: "Voulez-vous vraiment supprimer ce fichier ?",
  msg_mod_deleted: "Mod supprimé !",
  msg_java_not_found_prompt: "Java introuvable ou incorrect ! Voulez-vous installer automatiquement Java ",
  msg_java_installed_success: "Java installé avec succès !",
  discord_idle: "Prépare sa prochaine survie",
  msg_dl_complete: "Téléchargement terminé !",
  msg_loading: "Chargement...",
  lbl_never: "Jamais",
  lbl_copy_suffix: " - Copie",
  msg_err_pseudo_req: "Le pseudo est obligatoire !",
  ph_search_catalog: "Rechercher dans le catalogue...",
  msg_no_results_mc: "Aucun résultat trouvé pour Minecraft",
  lbl_author: "Auteur",
  tt_visibility: "Comportement de la fenêtre du launcher quand le jeu se lance : la garder ouverte, la minimiser, ou la masquer complètement.",
  tt_discord_rpc: "Affiche à quoi vous jouez sur votre profil Discord (Rich Presence). Désactivez si vous souhaitez rester discret.",
  tt_jvm_args: "Arguments transmis directement à la JVM Java avant le lancement. Réservé aux utilisateurs avancés. Exemple : -XX:HeapDumpPath=... -Dfml.ignoreInvalidMinecraftCertificates=true",
  tt_eco_mode: "Désactive les effets visuels (flou, transparence, animations) pour soulager la carte graphique.",
  lbl_change_version: "Version & Loader",
  lbl_mc_version: "Version MC",
  txt_version_warning: "⚠ Changer la version supprimera les fichiers du jeu et forcera leur retéléchargement.",
  msg_version_changed: "Version changée ! Les fichiers seront retéléchargés au prochain lancement.",
  msg_loader_no_compat: "Ce loader n'est pas encore disponible pour cette version. Passé en Vanilla.",
  msg_no_loader_compat: "Incompatible avec cette version",
  msg_err_loader_versions: "Erreur de chargement des versions",
};

const defaultEn = {
  toolbar_add: "Add Instance",
  toolbar_import: "Import",
  toolbar_builder: "Create a Modpack",
  toolbar_catalog: "Content Catalog",
  toolbar_settings: "Global Settings",
  toolbar_logs: "Show Logs",
  toolbar_manage: "Manage",
  toolbar_stats: "Statistics",
  search_inst: "Search instance...",
  sort_name: "Sort by Name",
  sort_last: "Last Played",
  sort_time: "Play Time",
  panel_title: "Select an instance",
  panel_time: "Time:",
  panel_last: "Last:",
  btn_launch: "Play",
  btn_stop: "Force Stop",
  btn_settings: "Instance Settings",
  btn_mods: "Mods Manager",
  btn_saves: "View Worlds",
  btn_gallery: "Screenshots Gallery",
  btn_folder: "Instance Folder",
  btn_delete: "Delete",
  btn_copy: "Copy Instance",
  btn_export: "Export Instance",
  status_ready: "Ready",
  modal_cancel: "Cancel",
  modal_save: "Save",
  modal_close: "Close",
  modal_apply: "Apply",
  modal_create: "Create",
  modal_add: "Add",
  btn_search: "Search",
  tab_gen: "General",
  tab_mods: "Mods",
  tab_shaders: "Shaders",
  tab_resourcepacks: "Resource Packs",
  tab_servers: "Servers",
  tab_backups: "Backups",
  tab_java: "Configuration",
  tab_notes: "Notes",
  tab_updates: "Updates",
  btn_check_launcher_updates: "Check for updates",
  msg_up_to_date: "The launcher is up to date.",
  msg_update_found: "An update was found",
  msg_download_update: "Do you want to download it in the background?",
  lbl_backup_mode: "World Auto-Backups",
  lbl_backup_limit: "Number of backups to keep:",
  opt_none: "Disabled",
  opt_launch: "On game launch",
  opt_close: "On game close",
  txt_backup_desc: "The launcher will automatically keep your latest backups in the 'backups' folder.",
  btn_open_backups: "Open Backups Folder",
  lbl_lang: "Launcher Language",
  lbl_ram: "Allocated RAM (MB):",
  lbl_java: "Default Java Path",
  btn_scan: "Scan",
  lbl_fav_server: "Favorite Server",
  lbl_beta: "Show Betas",
  lbl_loader: "Loader Type",
  lbl_loader_version: "Loader Version",
  lbl_inst_name: "Instance Name",
  lbl_installed_mods: "Installed Mods",
  lbl_installed_shaders: "Your Shaders",
  lbl_installed_rps: "Your Resource Packs",
  btn_check_updates: "Check for Updates",
  btn_dl_mods: "Download new mods",
  lbl_width: "Width",
  lbl_height: "Height",
  lbl_jvm: "JVM Arguments",
  lbl_offline: "Add Offline Profile",
  tab_appearance: "Appearance",
  lbl_accent: "Accent Color",
  lbl_bg: "Background Image",
  btn_browse: "Browse",
  btn_clear: "Clear",
  lbl_blur: "Background Blur",
  lbl_darkness: "Background Darkness",
  lbl_panel_opacity: "Interface Opacity (Panels)",
  lbl_group: "Instance Folder / Category",
  msg_mod_added: "Successfully added to the instance!",
  msg_select_inst: "Please select an instance first!",
  msg_search_java: "Searching for Java...",
  msg_java_found: "Java version(s) found.",
  msg_extract_java: "Extracting Java...",
  msg_err_java: "Java Error",
  msg_backup: "Creating backup...",
  msg_no_screen: "No screenshots.",
  msg_launching: "Launching ",
  msg_check_java: "Verifying Java...",
  msg_sync_servers: "Synchronizing servers...",
  msg_install_fabric: "Installing Fabric...",
  msg_prep_files: "Preparing files...",
  msg_dl: "Downloading: ",
  msg_game_stop: "Game stopped",
  msg_conn_ms: "Logging in...",
  ms_device_title: "Microsoft sign-in",
  ms_device_help: "Copy the code below, open the Microsoft page, then enter the code when the site asks for it.",
  ms_device_copy: "Copy code",
  ms_device_open: "Open Microsoft page",
  ms_device_copied: "Code copied to clipboard.",
  ms_device_status_1: "Waiting: confirm the code on the Microsoft website.",
  ms_device_status_2: "Finishing in the launcher (Xbox / Mojang servers)… This can take around 10 seconds.",
  ms_device_footer: "You can close the browser tab after sign-in is accepted ; this window closes when the account is saved.",
  ms_device_cancel: "Cancel",
  ms_device_cancelled: "Microsoft sign-in cancelled.",
  msg_err_ms: "Microsoft Error: ",
  msg_err_sys: "System Error: ",
  msg_remove_acc: "Remove this account?",
  msg_copy: "Copying...",
  msg_delete_inst: "Delete instance?",
  msg_compress: "Compressing...",
  msg_extract: "Extracting...",
  msg_check_updates: "Checking for updates...",
  msg_updating: "Updating: ",
  msg_mods_updated: "mod(s) updated!",
  msg_mods_uptodate: "Mods already up to date!",
  msg_dl_mod: "Downloading...",
  msg_no_compat: "No compatible file.",
  msg_deps: "Downloading dependencies...",
  msg_install_success: "Installation successful!",
  msg_err_dl: "Download error.",
  msg_ping: "Ping...",
  msg_online: "Online",
  msg_offline: "Offline",
  msg_err_ping: "Error",
  msg_no_mods: "No local mods installed.",
  msg_no_shaders: "No shaders installed.",
  msg_no_rps: "No resource packs installed.",
  msg_no_servers: "No saved servers.",
  msg_no_acc: "No profiles saved.",
  opt_modpack: "Modpacks",
  btn_install: "Install",
  msg_dl_mods_pack: "Downloading mods",
  msg_logs_copied: "Logs copied to clipboard!",
  msg_err_mrpack_invalid: "Not a valid .mrpack file.",
  msg_err_mrpack: "Modpack Error: ",
  btn_copy_logs: "Copy",
  modal_confirm: "Confirmation",
  btn_yes: "Yes",
  btn_no: "No",
  msg_err_cf: "CurseForge (.zip) modpacks are blocked by Overwolf restrictions. Use Modrinth (.mrpack) instead!",
  msg_err_path: "Error: Path not found (Run the app via npm start!)",
  msg_err_format: "Unsupported format! (.mrpack, .zip, .jar, .png)",
  modal_worlds_title: "Worlds Manager",
  msg_no_worlds: "No worlds found.",
  btn_world_backup: "Backup",
  btn_world_copy: "Copy",
  msg_copy_world_loading: "Copying world...",
  msg_world_copied: "World copied successfully!",
  msg_delete_world_confirm: "Are you sure you want to permanently delete this world?",
  msg_world_deleted: "World deleted!",
  msg_world_backedup: "Backup created in 'backups' folder!",
  lbl_folder: "Folder: ",
  lbl_created: "Created on: ",
  lbl_played: "Last played: ",
  modal_stats_title: "Dashboard",
  stat_total_time: "Total playtime",
  stat_total_instances: "Instances created",
  stat_total_mods: "Mods installed",
  stat_fav_instance: "Favorite instance: ",
  stat_disk_usage: "Disk space used",
  txt_players: "Players",
  btn_auto_ram: "Optimize",
  tt_auto_ram: "Analyzes your PC and mods to allocate perfect RAM (Min 4GB).",
  msg_ram_optimized: "RAM optimized to ",
  modal_updates_title: "Updates Available",
  msg_updates_available: "The following mods will be updated:",
  btn_update_all: "Install All",
  msg_no_updates: "All mods are up to date!",
  lbl_options_profile: "Options Profile (options.txt)",
  txt_options_desc: "Set an instance's options as default for future instances.",
  btn_save_options: "Set as default",
  msg_options_saved: "Options profile saved!",
  msg_no_options_found: "No options.txt found. Launch the game at least once on this instance!",
  msg_files_added: "file(s) added!",
  modal_import_mc: "Import Official World",
  btn_import_official_world: "Import from .minecraft",
  msg_no_mc_worlds: "No worlds found in .minecraft",
  msg_world_imported: "World imported successfully!",
  lbl_sync_options: "Keybinds & Options",
  txt_sync_options: "Overwrite settings with your default profile.",
  btn_sync_now: "Inject",
  msg_force_sync_success: "Options synced successfully!",
  msg_force_sync_error: "No default profile set in Global Settings.",
  lbl_visibility: "Launcher behavior on launch",
  opt_keep: "Keep open",
  opt_hide: "Hide launcher (Ghost Mode)",
  btn_auto_connect: "Auto",
  msg_warn_deps: "Potential missing dependency: ",
  btn_show: "Show",
  btn_hide: "Hide",
  lbl_news: "Minecraft News",
  msg_server_search: "Searching for server",
  msg_server_offline_desc: "The server is currently offline or unreachable.",
  msg_server_error: "Connection error to",
  lbl_players: "players",
  modal_export_zip: "Full Export (.zip)",
  txt_export_zip_desc: "Contains absolutely all your mods and worlds (Large file).",
  modal_export_mrpack: "Light Export (.mrpack)",
  txt_export_mrpack_desc: "Generates a tiny file ideal for sharing with friends.",
  lbl_live_stats: "System Monitoring",
  lbl_live_ram: "Global RAM:",
  lbl_live_cpu: "CPU Load:",
  msg_mrpack_analyze: "Analyzing mods and generating .mrpack...",
  msg_mrpack_success: ".mrpack export successful!",
  msg_mrpack_error: "Error during .mrpack export",
  lbl_discord_playing: "Playing on",
  lbl_discord_solo: "In game",
  btn_discord_download: "Download Gens Launcher",
  msg_dl_browser: "Secure download link... Opening browser.",
  msg_cf_api_req: "CurseForge requires an API Key.\nAdd it in the Launcher Global Settings.",
  msg_cf_api_invalid: "Invalid CurseForge API Key or network error.",
  lbl_warning: "[!]",
  lbl_accounts_title: "Accounts",
  lbl_add_microsoft: "Add Microsoft",
  lbl_add_offline: "Add Offline",
  lbl_use_account: "Use Account",
  lbl_skin_cape: "Skin & Cape",
  lbl_active_acc: "Active",
  modal_skin_title: "3D Skin Viewer",
  btn_test_skin: "Test a Skin (Preview)",
  btn_export_skin: "Export current Skin",
  btn_change_mojang: "Change on Minecraft.net",
  tip_skin_3d: "💡 Tip: Click and drag to rotate. Scroll to zoom.",
  btn_dl_shaders: "Download new shaders",
  btn_dl_rps: "Download new packs",
  ph_java_local: "Leave empty to use global",
  lbl_group_general: "General",
  lbl_current_version: "Current version:",
  ph_inst_name: "My Survival",
  ph_filter_logs: "Filter logs...",
  msg_calc: "Calculating...",
  lbl_gb: "GB",
  msg_open_mp: "Opening modpack page...",
  msg_dl_mp: "Downloading modpack...",
  msg_install_mp: "Installing modpack...",
  msg_patch_notes: "Bug fixes and improvements.",
  msg_update_ready: "Download complete! Do you want to restart the launcher to install the update?",
  lbl_cf_api: "CurseForge API Key (Optional)",
  txt_cf_api_desc: "Required only to use the CurseForge catalog. Get a free key on EternalDeveloper.",
  msg_err_name_req: "Instance name is required!",
  msg_profile_disabled: "Default profile disabled.",
  msg_err_install_loader: "Cannot install loader for this version.",
  msg_force_stop_sent: "Force stop request sent.",
  lbl_discord_rpc: "Discord RPC (In-game status)",
  lbl_multi_inst: "Multi-instance Launch",
  opt_enabled: "Enabled",
  opt_disabled: "Disabled",
  btn_folder_inst: "Instance Folder",
  btn_folder_saves: "Worlds Folder",
  btn_folder_backups: "Backups Folder",
  btn_folder_screens: "Screenshots Folder",
  btn_restore: "Restore",
  msg_restore_confirm: "Do you really want to restore \"{name}\"?\n\n⚠️ The current world will be deleted and replaced!",
  msg_restore_loading: "Restoring backup...",
  msg_restore_success: "World restored successfully!",
  msg_restore_err: "Error during restoration: ",
  msg_no_backups: "No backups found.",
  msg_del_screen_confirm: "Do you really want to delete this screenshot?",
  msg_screen_deleted: "Screenshot deleted.",
  msg_del_screen_err: "Error deleting: ",
  modal_restore_title: "Restore a backup",
  lbl_auto_update: "Download updates automatically",
  msg_update_dl_prompt: "A new launcher version is available. Do you want to download it?",
  msg_update_restart: "Update ready! Do you want to restart the launcher now?",
  lbl_running: "Running",
  msg_req_mc_120: "Requires Minecraft 1.20+",
  msg_shader_deleted: "Shader deleted!",
  msg_rp_deleted: "Pack deleted!",
  msg_err_delete: "Error while deleting",
  msg_game_running: "Game is running...",
  msg_install_quilt: "Installing Quilt...",
  discord_in_menu: "In menus",
  discord_playing_on: "Playing on",
  discord_playing_solo: "Playing Singleplayer",
  lbl_servers_profile: "Servers Profile (servers.dat)",
  txt_servers_desc: "Automatically copies servers from this instance to all new instances.",
  btn_save_default: "Set as default",
  opt_none_disable: "None (Disable)",
  msg_profile_saved: "Profile saved!",
  lbl_java_opti: "Java Optimization Profile (Anti-Lag)",
  txt_java_opti_desc: "Select a profile to automatically inject the best arguments.",
  opt_java_none: "None (Standard)",
  opt_java_aikar: "Aikar's Flags (Recommended for most)",
  opt_java_zgc: "ZGC (Low latency - Requires Java 21+)",
  desc_java_none: "Standard: Lets the game manage memory with the default settings of your Java version.",
  desc_java_aikar: "Aikar's Flags: The most famous arguments in the Minecraft community. They force the game to clean RAM intelligently. Advantage: Almost completely removes 'lag spikes'. Perfect for heavy modpacks.",
  desc_java_zgc: "Z Generational (ZGC): Ultra-modern Java technology. Cuts RAM processing time by 10. Advantage: Almost invisible pause times. Ideal for competitive PvP and absolute smoothness. (Note: Only works if the instance uses Java 21 or higher).",
  stat_mobs: "Mobs Killed",
  stat_distance: "Distance (Walked)",
  stat_jumps: "Jumps",
  lbl_km: "km",
  lbl_cache_title: "Temporary Files (Cache)",
  txt_cache_desc: "Forge installers, Java archives, and old exports.",
  lbl_freed_space: "Space to free:",
  btn_clean: "Clean",
  lbl_graph_title: "⏱ Playtime — Last 7 days",
  lbl_new_version: "New version available:",
  btn_start_update: "Download and Install",
  msg_update_found_bg: "Update found! Downloading in background...",
  msg_login_success: "Login successful!",
  msg_skin_exported: "Skin exported successfully!",
  msg_err_skin_export: "Error exporting skin.",
  msg_err_reserved_name: "This name is invalid as it is reserved by the system.",
  msg_err_similar_name: "An instance with a similar name (same folder) already exists!",
  msg_err_create_folder: "System error: Cannot create the folder.",
  msg_err_rename_folder: "System error: Cannot rename the folder.",
  modal_builder_title: "Custom Modpack Creator",
  lbl_modpack_name: "Modpack Name",
  ph_modpack_name: "My Custom Modpack",
  lbl_version: "Version",
  lbl_your_selection: "Your selection",
  btn_create_install: "Create & Install",
  opt_mods_type: "Mods",
  opt_shaders_type: "Shaders",
  opt_rp_type: "Resource Packs",
  ph_search_modrinth: "Search on Modrinth...",
  msg_builder_no_name: "Give your Modpack a name!",
  msg_builder_no_mods: "Add at least one item!",
  msg_builder_name_taken: "An instance with this name already exists.",
  msg_builder_creating: "Creating instance...",
  msg_builder_downloading: "Downloading:",
  msg_builder_success: "Modpack created successfully!",
  msg_builder_searching: "Searching...",
  msg_builder_no_results: "No results for this version / loader.",
  msg_builder_empty_pack: "The pack is empty.",
  msg_builder_search_err: "Search error.",
  btn_added: "Added",
  btn_add_to_pack: "Add",
  lbl_type_mod: "Mod",
  lbl_type_shader: "Shader",
  lbl_type_pack: "Resource Pack",
  msg_crash_prompt: "The game crashed! \n\nThe analyzer detected that [ {mod} ] is the cause.\nDo you want to disable it?",
  msg_analyze_cf: "Analyzing CurseForge Modpack...",
  msg_prep_loader: "Preparing ",
  msg_dl_loader: "Downloading ",
  msg_drop_install: "Drop to install",
  lbl_mc_console: "Minecraft Console",
  modal_icon_gallery_title: "Icon Gallery",
  lbl_eco_mode: "Eco Mode (Performance)",
  opt_eco_disabled: "Disabled (Recommended)",
  opt_eco_enabled: "Enabled (For low-end PCs)",
  lbl_java_25: "Java 25",
  desc_java_25: "For Minecraft 26.1 and +",
  lbl_java_21: "Java 21",
  desc_java_21: "For Minecraft 1.20.5 to 26.1",
  lbl_java_17: "Java 17",
  desc_java_17: "For Minecraft 1.17 to 1.20.4",
  lbl_java_8: "Java 8",
  desc_java_8: "For Minecraft 1.16.5 and older",
  btn_java_dl: "Download",
  btn_java_installed: "Installed",
  lbl_ms_account: "Microsoft Account",
  lbl_offline_account: "Offline (Cracked)",
  msg_skin_preview: "Skin preview loaded in 3D!",
  msg_delete_confirm: "Are you sure you want to delete this file?",
  msg_mod_deleted: "Mod deleted!",
  msg_java_not_found_prompt: "Java missing or incorrect! Do you want to automatically install Java ",
  msg_java_installed_success: "Java installed successfully!",
  discord_idle: "Preparing for the next survival",
  msg_dl_complete: "Download complete!",
  msg_loading: "Loading...",
  lbl_never: "Never",
  lbl_copy_suffix: " - Copy",
  msg_err_pseudo_req: "Username is required!",
  ph_search_catalog: "Search in catalog...",
  msg_no_results_mc: "No results found for Minecraft",
  lbl_author: "Author",
  tt_visibility: "Behavior of the launcher window when the game launches: keep it open, minimize it, or hide it completely.",
  tt_discord_rpc: "Shows what you are playing on your Discord profile (Rich Presence). Disable if you want to stay discreet.",
  tt_jvm_args: "Arguments passed directly to the Java JVM before launch. For advanced users only. Example: -XX:HeapDumpPath=... -Dfml.ignoreInvalidMinecraftCertificates=true",
  tt_eco_mode: "Disables visual effects (blur, transparency, animations) to reduce GPU load.",
  lbl_change_version: "Version & Loader",
  lbl_mc_version: "MC Version",
  txt_version_warning: "⚠ Changing the version will delete game files and force a re-download on next launch.",
  msg_version_changed: "Version changed! Files will be re-downloaded on next launch.",
  msg_loader_no_compat: "This loader is not yet available for this version. Switched to Vanilla.",
  msg_no_loader_compat: "Incompatible with this version",
  msg_err_loader_versions: "Failed to load versions",
};

export function setupLang() {
    function syncLangFile(filePath, defaultObj) {
        let current = {};
        if (fs.existsSync(filePath)) {
            try { current = JSON.parse(fs.readFileSync(filePath, "utf8")); } catch (e) {}
        }
        let updated = false;
        for (let key in defaultObj) {
            if (current[key] === undefined) {
                current[key] = defaultObj[key];
                updated = true;
            }
        }
        if (updated || !fs.existsSync(filePath)) {
            fs.writeFileSync(filePath, JSON.stringify(current, null, 2));
        }
    }

    syncLangFile(path.join(store.langDir, "fr.json"), defaultFr);
    syncLangFile(path.join(store.langDir, "en.json"), defaultEn);

    window.applyTranslations = () => {
        document.querySelectorAll("[data-i18n]").forEach((el) => {
            const key = el.getAttribute("data-i18n");
            if (store.currentLangObj[key]) {
                if (el.tagName === "INPUT" && el.type === "text") el.placeholder = store.currentLangObj[key];
                else el.innerText = store.currentLangObj[key];
            }
        });
        
        document.querySelectorAll("[data-i18n-title]").forEach((el) => {
            const key = el.getAttribute("data-i18n-title");
            if (store.currentLangObj[key]) el.title = store.currentLangObj[key];
        });

        document.querySelectorAll("[data-i18n-tooltip]").forEach((el) => {
            const key = el.getAttribute("data-i18n-tooltip");
            if (store.currentLangObj[key]) el.setAttribute("data-tooltip", store.currentLangObj[key]);
        });

        const cv = document.getElementById("current-app-version");
        if (cv) cv.innerText = "v" + window.api.version;
        
        if (window.updateLaunchButton) window.updateLaunchButton();
        if (window.updateRPC) window.updateRPC();
    };

    window.loadLanguage = (code) => {
        const p = path.join(store.langDir, `${code}.json`);
        if (fs.existsSync(p)) {
            store.currentLangObj = JSON.parse(fs.readFileSync(p, "utf8"));
            window.applyTranslations();
        }
    };

    window.changeLanguage = (code) => {
        store.globalSettings.language = code;
        fs.writeFileSync(store.settingsFile, JSON.stringify(store.globalSettings, null, 2));
        window.loadLanguage(code);
    };

    window.saveFirstLaunch = () => {
        const code = document.getElementById("first-launch-lang").value;
        store.globalSettings.language = code;
        fs.writeFileSync(store.settingsFile, JSON.stringify(store.globalSettings, null, 2));
        window.loadLanguage(code);
        document.getElementById("modal-first-launch").style.display = "none";
    };

    window.populateLangDropdown = () => {
        const select = document.getElementById("global-lang");
        select.innerHTML = "";
        fs.readdirSync(store.langDir).filter((f) => f.endsWith(".json")).forEach((f) => {
            const code = f.replace(".json", "");
            const opt = document.createElement("option");
            opt.value = code;
            opt.innerText = code.toUpperCase();
            if (code === store.globalSettings.language) opt.selected = true;
            select.appendChild(opt);
        });
    };
}